Reencuar enviament de correus erroni per limitacio de 30 al min
gisce/poweremail pull request #150
Opened 2024-03-27 10:48 UTC by ikeeeeer6

2024-04-09 06:53 UTC, BellaCs requested changes

2024-04-09 06:53 UTC, BellaCs commented on migrations/5.0.24.5.0/post-0001_cron_rencuar_emails.py
> +    pool.get("poweremail.mailbox")._auto_init(cursor, context={'module': 'poweremail'})
no fa falta autoinit, no toques el columns

2024-04-09 06:53 UTC, BellaCs commented on poweremail_mailbox.py
> +        for email_id in emails_ids:
pots fer tant el write com el historise amb tots de cop, el loop es innecesari

2024-04-09 07:05 UTC, BellaCs commented on poweremail_mailbox.py
> +        self.write(cursor, uid, emails_ids, {'state': 'na', 'folder': 'outbox'}, context)
el context millor sempre paramed name

2024-04-09 07:05 UTC, BellaCs commented on poweremail_mailbox.py
> +        emails_ids = self.search(cursor, uid, [('history', 'like', '%None%')])
falta el context

2024-05-22 14:51 UTC, eberloso approved these changes

2024-05-22 14:51 UTC, merged