Template attachments
gisce/poweremail pull request #9
Opened 2012-11-28 11:30 UTC by ecarreras

This commit is an adaptation from Àngel Àlvarez one[1].

[1] http://bazaar.launchpad.net/~nan-tic/poweremail/nan_poweremail/revision/208

2021-06-11 07:07 UTC, lcbautista commented
Creo que no funciona. La funcionalidad como tal funciona, adjunta correctamente el documento, pero rompe el funcionamiento del asistente de envío de correos (por ejemplo, al enviar una factura de un cliente, el pdf no se adjunta).

2022-08-23 13:58 UTC, a-orellana commented
Cal la PR https://github.com/gisce/erp/pull/15072.
Afegeix reports de demo al mòdul base de l'erp necessaris per passar testos.

2022-08-24 07:23 UTC, lcbautista requested changes

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +        proxy = self.pool.get('ir.attachment')
change variable name

2022-08-24 07:23 UTC, lcbautista commented on poweremail_send_wizard.py
> +        attach_obj = self.pool.get('ir.attachment')
move code up

2022-08-24 07:23 UTC, lcbautista commented on poweremail_send_wizard.py
> +        for attach in attach_obj.browse(cr, uid, attach_ids, context):
context=context

2022-08-24 07:23 UTC, lcbautista commented on poweremail_send_wizard.py
> +                search_params += [
use .append

2022-08-24 07:23 UTC, lcbautista commented on poweremail_send_wizard.py
> +                attach_ids = attach_obj.search(cr, uid, search_params,
improve indentation

2022-08-24 07:23 UTC, lcbautista commented on poweremail_send_wizard.py
> +            new_id = attach_obj.copy(cr, uid, attach.id, {
create new variable for values

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +            res[template_id] = proxy.search(cr, uid, search_params, context=context )
delete blank space

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +            self.write(cursor, uid, pm_template_id, {'attachment_ids': value}, context=context)
review if write must be on attachment_ids

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +        'ir_attachment_ids': fields.function(_fnc_ir_attachment_ids, fnct_inv= fnct_inv_attachment_ids, method=True, type='one2many', relation='ir.attachment', string='Attachments'),
indent < 80chars

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +        data['model'] = template.model_int_name
reduce

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +            new_id = attachment_obj.copy(cursor, user, attach.id, attachment_vals)
missing context

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +            self.pool.get('poweremail.mailbox').write(cursor, user, mail.id, mailbox_vals, context=context)
move model obj up in a new variable

2022-08-24 07:23 UTC, lcbautista commented on poweremail_template.py
> +        mailbox_id = self.pool.get('poweremail.mailbox').create(cursor, user, mailbox_values, context=context)
new variable for mailbox obj and move up

2022-08-26 08:47 UTC, lcbautista requested changes

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            signature = res_users_obj.read(cr, uid, uid, ['signature'], context)['signature']
context=context

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +        context.update({'src_rec_id': src_rec_id})
create new context (avoid modify the original)

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            return res_users_obj.read(cr, uid, uid, ['context_lang'], context)['context_lang']
context=context

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            data['model'] = ir_model_obj.browse(cr, uid, screen_vals['rel_model'], context=context).model
:thinking: does this line makes sense?

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +    def check_template_report(self, cr, uid, template, vals, screen_vals, mail_id, report_record_ids, src_rec_id, context=None):
change to create_report_attachment

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            report_model_ids = model_obj.search(cr, uid, search_params)
missing context

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            (result, format) = service.create(cr, uid, report_model_ids, data, context)
context=context

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +                continue
avoid cotinue statement

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            attachment_id = attach_obj.create(cr, uid, attach_vals, context)
context=context

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +            }, context)
context=context and use new variable for copy values

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +        if template.partner_event and self._get_template_value(cr, uid, 'partner_event', context):
check if context is a named parameter

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +                mailgate_obj.create(cr, uid, values, context)
context=context

2022-08-26 08:47 UTC, lcbautista commented on poweremail_send_wizard.py
> +                mailbox_obj.write(cr, uid, mail_id, mailbox_vals, context)
context=context

2022-08-26 08:47 UTC, lcbautista commented on tests/__init__.py
> +            mock_function_2.return_value = mail_id
avoid create mail from code, create mail from data XML

2022-08-26 12:44 UTC, lcbautista commented
Succesfully tested

2022-08-26 12:44 UTC, merged